### ISSUE TITLE
[Incident] Server down due to disk full and accidental docker volume deletion

### ISSUE THREAD

**Issue by aktech** [Quansight/open-gpu-server#19]
There was a degraded performance of the GPU Server this morning, due to the fact that disk ran out of space, causing MySQL, RabbitMQ unresponsive and hence causing degraded and no-response for most OpenStack APIs.

In an effort to fix this, I accidentally deleted the DB docker volume. This has caused losing following important configurations:

- users
- flavors
- images
- network configuration

**Comment by aktech** [comment]
I have restored the following so far:

- users
- flavors
- images

**Comment by aktech** [comment]
Server is back online, restored networking configurations as wel.

**Comment by aktech** [comment]
Runners back in operation:

<img width="1117" alt="Screenshot 2023-12-01 at 8 02 07 pm" src="https://github.com/Quansight/open-gpu-server/assets/5647941/567ced20-4ddd-491c-9385-19720e9a654e">

Closing this issue.

**Comment by jakirkham** [comment]
Thanks Amit! 🙏
