### ISSUE TITLE
Server is down

### ISSUE THREAD

**Issue by jaimergp** [Quansight/open-gpu-server#24]
Confirmed outage. 

Investigating root cause and initiating recovery process.

**Comment by aktech** [comment]
We're back in business. Server is up and running.

**Comment by isuruf** [comment]
Thanks everyone for fixing this.

**Comment by jakirkham** [comment]
Would it make sense to setup some sort of status page?

**Comment by aktech** [comment]
Yep, there is one: https://ci-status.quansight.dev/

**Comment by jaimergp** [comment]
> Would it make sense to setup some sort of status page?

Added it to conda-forge.org/status too via https://github.com/conda-forge/status/pull/161.
