### ISSUE TITLE
BUG: Runners build from .ci_support in main branch even when triggered in pull request

### ISSUE THREAD

**Issue by carterbox** [Quansight/open-gpu-server#32]
In https://github.com/conda-forge/libmagma-feedstock/pull/18, I have opened a pull request to update the package to the latest version and drop builds for CUDA 11.2. However, the runners building this pull request start a job for CUDA 11.2 anyways; these jobs exit with an error because the config file for the CUDA 11.2 build is missing from .ci_support due to the fact that they have been removed in the pull request branch.

Starting jobs which will always fail will, in theory, prevent automerge tasks from completing successfully.

**Comment by carterbox** [comment]
If I add an explicit skip to the recipe for CUDA 11.2 and rerender the job is removed, so this probably just means 11.2 hasn't been removed yet from the template on conda-smithy.

**Comment by jaimergp** [comment]
I do see the matrix entries in https://github.com/conda-forge/libmagma-feedstock/pull/18/files#diff-2c0e39bc014e056be855742e3ff5cc61ce0e4be5b6e1f4399af608b6aa22d8df being removed, so not sure what's going on. Maybe cirun is triggering jobs from the matrix in `main`? Pinging @aktech

**Comment by jaimergp** [comment]
Hm, are you sure it wasn't just a missing rerender?

**Comment by carterbox** [comment]
I'm not able to reproduce the issue, so you're probably right about missing rerender or using old conda-smithy version.

**Comment by jakirkham** [comment]
Not sure how we are checking out PRs currently, but the usual way to do this is to checkout the `merge` ref, which is a GitHub generated merge commit between the PR branch and the base branch the PR is targeting. The other one to check is the `head` ref, which is the latest commit on the PR. So if we assigned these to local branches called `pr_head_commit` and `pr_merge_commit`, this would look like...

```
git fetch <base remote> pull/<pr#>/head:pr_head_commit
git fetch <base remote> pull/<pr#>/merge:pr_merge_commit
```

Here is some relevant code from [the conda-forge linter doing the same thing]( https://github.com/conda-forge/conda-forge-webservices/blob/4856c4aacf0d8e068c0f35ee3346642b0f173234/conda_forge_webservices/linting.py#L173-L189 ). Note sometimes the merge ref doesn't exist (like there is a conflict), which the conda-forge linter will raise

**Comment by jaimergp** [comment]
We are using the [official action](https://github.com/conda-forge/conda-smithy/blob/7b0b83038ae6c012c72bc13cca6641fb81dc7e08/conda_smithy/templates/github-actions.yml.tmpl#L92-L97), nothing fancy. I would assume it does The Right Thing without further complication, I think?
