### ISSUE TITLE
Permissions issue with flash-attn-feedstock

### ISSUE THREAD

**Issue by carterbox** [Quansight/open-gpu-server#45]
[@Quansight/open-gpu-server](https://github.com/orgs/Quansight/teams/open-gpu-server)

We are trying to build flash-attn reliably for more than one CUDA architecture. We recently were approved to use the cirun-openstack-cpu-xlarge runner and have [merged the corresponding PR](https://github.com/conda-forge/flash-attn-feedstock/pull/16).

The maintainers of the feedstock @carterbox and @weiji14 are [listed in the access json.](https://github.com/Quansight/open-gpu-server/blob/main/access/conda-forge-users.json) I have double checked that the id numbers are correctly listed in the conda-forge-users.json.

However, the [post-merge main branch](https://github.com/conda-forge/flash-attn-feedstock/runs/31308087750) and other open PRs fail to build. There is an error message from Cirun that users are not authorized.

```
{
    "error": "User not authorized for the requested runners, user not present in 'users' list."
}
```

The github actions for "Build conda package" shows jobs waiting in the queue. Is the queue full? Is there somewhere that I can view the queue? Is the user access list out of sync? Thanks!

**Comment by carterbox** [comment]
I don't think that my team mention works because I am not part of the Quantsight org.

**Comment by isuruf** [comment]
Fixed with the merging of https://github.com/conda-forge/.cirun/pull/23

**Comment by jakirkham** [comment]
Thanks Isuru! 🙏
